
<!-- BEGIN Inchoo Facebook Connect -->
<div id="fb-root"></div>
<script src="<?php echo $this->isSecure() ? 'https://' : 'http://' ?>connect.facebook.net/en_US/all.js" type="text/javascript"></script>
<script type="text/javascript">
FB.init({ apiKey:<?php echo json_encode($this->getApiKey()) ?>, cookie:true, xfbml: true });

document.observe('click', function(e){
	var target = event.findElement('a[rel^=facebook-connect]') || event.findElement('button[rel^=facebook-connect]');
	if (target && target.readAttribute('rel')=='facebook-connect') {
		e.stop();
		FB.login(function(response){
			if(response.status=='connected') setLocation('<?php echo $this->getConnectUrl() ?>');
		}, {perms:<?php echo $this->getRequiredPermissions() ?>});
	}
});

<?php /*
document.observe("dom:loaded", function(){
	$$('.facebook-connect').each(function(el){
			el.observe('click',function(e){
				Event.stop(e);
				FB.login(function(response){ 
					setLocation('<?php echo $this->getConnectUrl() ?>'); 
				}, {perms:<?php echo $this->getRequiredPermissions() ?>});
			}); 
	});
});
*/ ?>
</script>
<!-- END Inchoo Facebook Connect -->
